# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ReferenceApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReferenceApp
  pod 'TallyGoKit'

  target 'ReferenceAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReferenceApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReferenceApp-tvOS

  target 'ReferenceApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
